apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: api
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'api'
        static_configs:
          - targets: ['api-deployment:8000']

      - job_name: 'prometheus-exporter'
        static_configs:
          - targets: ['api-deployment:9100']
